/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-07-22 07:05:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class notice_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1721619752772L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1721631781752L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String noticeSeq = request.getParameter("seq"); // seq키의 값을 가져온다
	String noticeTitle = request.getParameter("title"); // title키의 값을 가져온다

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!-- 1. 탭 타이틀 세팅 -->\r\n");
      out.write("    <title>Starbucks Coffee Korea</title>\r\n");
      out.write("    <!-- 2. favicon(favorite icon) 세팅 -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./favicon.ico\" />\r\n");
      out.write("    <link rel=\"icon\" href=\"./favicon.png\" />\r\n");
      out.write("    <!-- 3. reset.css 세팅(cdn) -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- 4. 커스템 css파일 세팅(local) -->\r\n");
      out.write("    <link href=\"./css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- 5. 폰트 설정 -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- 6. 아이콘 설정 --> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("    <!-- 7. 오픈 그래프 설정(더 많은 속성을 보고 싶으면 https://ogp.me) -->\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"Starbucks\" />\r\n");
      out.write("    <meta property=\"og:title\" content=\"Starbucks Coffee Korea\" />\r\n");
      out.write("    <meta property=\"og:description\" content=\"스타벅스는 세계에서 가장 큰 다국적 커피 전문점으로, 64개국에서 총 23,187개의 매점을 운영하고 있습니다.\" />\r\n");
      out.write("    <meta property=\"og:image\" content=\"./images/starbucks_seo.jpg\" />\r\n");
      out.write("    <meta property=\"og:url\" content=\"https://starbucks.co.kr\" /> \r\n");
      out.write("    <!-- 8. 자바 스크립트 설정 -->\r\n");
      out.write("    <!-- <script src=\"https://code.jquery.com/jquery-3.7.1.js\" integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("    <script src=\"./js/jquery-3.7.1.js\"></script>\r\n");
      out.write("    <!-- lodash -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js\"></script>\r\n");
      out.write("    <!-- <script src=\"https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js\" integrity=\"sha512-WFN04846sdKMIP5LKNphMaWzU7YpMyCU245etK3g/2ARYbPK9Ub18eG+ljU96qKRCWh+quCY7yefSmlkQw1ANQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script> -->\r\n");
      out.write("    <!-- gsap js -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js\" integrity=\"sha512-IQLehpLoVS4fNzl7IfH8Iowfm5+RiMGtHykgZJl9AWMgqx0AmJ6cRWcB+GaGVtIsnC4voMfm8f2vwtY+6oPjpQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/ScrollToPlugin.min.js\" integrity=\"sha512-nTHzMQK7lwWt8nL4KF6DhwLHluv6dVq/hNnj2PBN0xMl2KaMm1PM02csx57mmToPAodHmPsipoERRNn4pG7f+Q==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/ScrollMagic.min.js\" integrity=\"sha512-8E3KZoPoZCD+1dgfqhPbejQBnQfBXe8FuwL4z/c8sTrgeDMFEnoyTlH3obB4/fV+6Sg0a0XF+L/6xS4Xx1fUEg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    <!-- swiper 6.8.4 -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.8.4/swiper-bundle.min.js\" integrity=\"sha512-BABFxitBmYt44N6n1NIJkGOsNaVaCs/GpaJwDktrfkWIBFnMD6p5l9m+Kc/4SLJSJ4mYf+cstX98NYrsG/M9ag==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.8.4/swiper-bundle.min.css\" integrity=\"sha512-aMup4I6BUl0dG4IBb0/f32270a5XP7H1xplAJ80uVKP6ejYCgZWcBudljdsointfHxn5o302Jbnq1FXsBaMuoQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <script defer src=\"./js/youtube.js\"></script>\r\n");
      out.write("    <script defer src=\"./js/main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("            <a href=\"/starbucks-homepage1\" class=\"logo\">\r\n");
      out.write("                <img src=\"./images/starbucks_logo.png\" alt=\"스타벅스\" />\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sub-menu\">\r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">Sign In</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">My Starbucks</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">Customer Service & Ideas</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">Find a Store</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"search\">\r\n");
      out.write("                    <input text=\"text\" placeholder=\"\"/>\r\n");
      out.write("                    <span class=\"material-symbols-outlined\">\r\n");
      out.write("                        search\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"main-menu\">\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                    <div class=\"item__name\">COFFEE</div>\r\n");
      out.write("                    <div class=\"item__contents\">\r\n");
      out.write("                        <div class=\"contents__menu\">\r\n");
      out.write("                            <ul class=\"inner\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <h4>커피</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>스타벅스 원두</li>\r\n");
      out.write("                                        <li>스타벅스 비아</li>\r\n");
      out.write("                                        <li>스타벅스 오리가미</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <h4>에스프레소 음료</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>도피오</li>\r\n");
      out.write("                                        <li>에스프레스 마키아또</li>\r\n");
      out.write("                                        <li>아메리카노</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <h4>커피 이야기</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>스타벅스 로스트 스펙트럼</li>\r\n");
      out.write("                                        <li>ㅁㅁㄴㅁㄴㅁ</li>\r\n");
      out.write("                                        <li>ㅌㅊㅍㅍㅊㅌㅍ</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"contents__texture\">\r\n");
      out.write("                            <div class=\"inner\">\r\n");
      out.write("                                <h4>나와 어울리는 커피 찾기</h4>\r\n");
      out.write("                                <p>스타벅스가 여러분에게 어울리는 커피를 찾아드립니다.</p>\r\n");
      out.write("                                <h4>최상의 커피를 즐기는 법</h4>\r\n");
      out.write("                                <p>여러가지 방법을 통해 다양한 풍미의 커피를 즐겨보세요</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                    <div class=\"item__name\">MENU</div>\r\n");
      out.write("                    <div class=\"item__contents\">\r\n");
      out.write("                        <div class=\"contents__menu\">\r\n");
      out.write("                            <ul class=\"inner\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <h4>음료</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>adsfasdf</li>\r\n");
      out.write("                                        <li>zxcvzxcvzxcv</li>\r\n");
      out.write("                                        <li>zxcvzxcv</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <h4>푸드</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>ㅋㅌㅊㅍㅋㅌㅊ</li>\r\n");
      out.write("                                        <li>ㅁㄴㅇㄹㅋㅌㅊㅍ</li>\r\n");
      out.write("                                        <li>ㅋㅌㅊ픀ㅌㅊ</li>\r\n");
      out.write("                                        <li>ㅋㅌㅊ픀ㅌㅊ</li>\r\n");
      out.write("                                        <li>ㅋㅌㅊ픀ㅌㅊ</li>\r\n");
      out.write("                                        <li>ㅋㅌㅊ픀ㅌㅊ</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"contents__texture\">\r\n");
      out.write("                            <div class=\"inner\">\r\n");
      out.write("                                <h4>스타벅스 티바나</h4>\r\n");
      out.write("                                <p>스타벅스가 찾아드립니다.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                    <div class=\"item__name\">STORE</div>\r\n");
      out.write("                    <div class=\"item__contents\">\r\n");
      out.write("                        <div class=\"contents__menu\"></div>\r\n");
      out.write("                        <div class=\"contents__texture\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                    <div class=\"item__name\">RESPONSEBILITY</div>\r\n");
      out.write("                    <div class=\"item__contents\">\r\n");
      out.write("                        <div class=\"contents__menu\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"contents__texture\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                    <div class=\"item__name\">MY STARRBUCKS REWARDS</div>\r\n");
      out.write("                    <div class=\"item__contents\">\r\n");
      out.write("                        <div class=\"contents__menu\"></div>\r\n");
      out.write("                        <div class=\"contents__texture\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"item\">\r\n");
      out.write("                    <div class=\"item__name\">WHAT'S NEW</div>\r\n");
      out.write("                    <div class=\"item__contents\">\r\n");
      out.write("                        <div class=\"contents__menu\"></div>\r\n");
      out.write("                        <div class=\"contents__texture\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"badges\">\r\n");
      out.write("            <div class=\"badge\">\r\n");
      out.write("                <img src='./images/badge1.jpg' alt=\"badge1\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"badge\">\r\n");
      out.write("                <img src='./images/badge2.jpg' alt=\"badge2\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("    ");

		System.out.println("공지사항 상세페이지 상단");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <section style=\"margin-top:120px;\">\r\n");
      out.write("    공지사항 상세페이지1 -> ");
      out.print( noticeSeq );
      out.write(':');
      out.write(' ');
      out.print( noticeTitle );
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("	");

		System.out.println("공지사항 상세페이지 하단");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("            <ul class=\"menu\">\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침1</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침2</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침3</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침4</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침5</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보처리방침6</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"btn-group\">\r\n");
      out.write("                <a href=\"#\" class=\"btn btn--white\">찾아오시는 길</a>\r\n");
      out.write("                <a href=\"#\" class=\"btn btn--white\">신규입점제의</a>\r\n");
      out.write("                <a href=\"#\" class=\"btn btn--white\">사이트 맵</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <span>사업자등록번호 201-81-21515</span>\r\n");
      out.write("                <span>(주)스타벅스 코리아 대표이사 이석구</span>\r\n");
      out.write("                <span>TEL : 02) 3015-1100 / FAX : 02) 3015-1106</span>\r\n");
      out.write("                <span>개인정보 책임자 : 강기원</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"copyright\">\r\n");
      out.write("                &copy; <span class=\"this-year\"></span> Starbucks Coffee Company. All rights reserved.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <img src=\"./images/starbucks_logo_only_text.png\" alt=\"starbucks footer logo\" class=\"logo\" />\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- 위로 가기 버튼 -->\r\n");
      out.write("    <div id=\"to-top\">\r\n");
      out.write("        <div class=\"material-symbols-outlined\">\r\n");
      out.write("            arrow_upward\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
